export const dynamic = 'force-dynamic'
export const runtime = 'nodejs'

import { NextRequest, NextResponse } from 'next/server'

const HS = 'https://api.hubapi.com'
const TOKEN = process.env.HUBSPOT_TOKEN

function auth() {
  return { Authorization: `Bearer ${TOKEN}`, 'Content-Type': 'application/json' }
}

// POST /api/save-to-hubspot
// Saves the AI-drafted email as a HubSpot note on the company + deal
export async function POST(req: NextRequest) {
  if (!TOKEN) return NextResponse.json({ error: 'HUBSPOT_TOKEN not configured' }, { status: 500 })

  const { subject, body, clientName, csmName, companyId, dealId } = await req.json()

  const noteBody = `📧 AI-DRAFTED EMAIL — Ready to send\n\nTo: ${clientName}\nCSM: ${csmName}\n\n---\nSUBJECT: ${subject}\n\n${body}\n\n---\nGenerated by Flowbox CS Dashboard. Copy subject + body above and send from your HubSpot email compose.`

  try {
    // 1. Create the note
    const noteRes = await fetch(`${HS}/crm/v3/objects/notes`, {
      method: 'POST',
      headers: auth(),
      cache: 'no-store',
      body: JSON.stringify({
        properties: {
          hs_note_body: noteBody,
          hs_timestamp: new Date().toISOString(),
        },
      }),
    })

    if (!noteRes.ok) {
      const err = await noteRes.text()
      console.error('HubSpot note creation failed:', err)
      return NextResponse.json({ error: 'Failed to create note in HubSpot', detail: err }, { status: 500 })
    }

    const note = await noteRes.json()
    const noteId = note.id

    // 2. Associate note with company
    if (companyId) {
      await fetch(`${HS}/crm/v4/objects/notes/${noteId}/associations/companies/${companyId}`, {
        method: 'PUT',
        headers: auth(),
        cache: 'no-store',
        body: JSON.stringify([{ associationCategory: 'HUBSPOT_DEFINED', associationTypeId: 190 }]),
      })
    }

    // 3. Associate note with deal
    if (dealId && dealId !== companyId) {
      await fetch(`${HS}/crm/v4/objects/notes/${noteId}/associations/deals/${dealId}`, {
        method: 'PUT',
        headers: auth(),
        cache: 'no-store',
        body: JSON.stringify([{ associationCategory: 'HUBSPOT_DEFINED', associationTypeId: 214 }]),
      })
    }

    const portalId = process.env.HUBSPOT_PORTAL_ID ?? '8988558'
    // Open the deal page (shows note in activity feed) — fall back to company page
    const hubspotUrl = dealId && dealId !== companyId
      ? `https://app.hubspot.com/contacts/${portalId}/deal/${dealId}`
      : `https://app.hubspot.com/contacts/${portalId}/company/${companyId}`

    return NextResponse.json({ success: true, noteId, hubspotUrl })
  } catch (err) {
    console.error('Save to HubSpot error:', err)
    return NextResponse.json({ error: String(err) }, { status: 500 })
  }
}
