export const dynamic = 'force-dynamic'
export const runtime = 'nodejs'

import { NextRequest, NextResponse } from 'next/server'

const HS = 'https://api.hubapi.com'
const TOKEN = process.env.HUBSPOT_TOKEN

function auth() {
  return { Authorization: `Bearer ${TOKEN}`, 'Content-Type': 'application/json' }
}

// POST /api/save-to-hubspot
// Saves the AI-drafted email as a HubSpot note on the company + deal
export async function POST(req: NextRequest) {
  if (!TOKEN) return NextResponse.json({ error: 'HUBSPOT_TOKEN not configured' }, { status: 500 })

  const { subject, body, clientName, csmName, companyId, dealId } = await req.json()

  const noteBody = `📧 AI-DRAFTED EMAIL — Ready to send\n\nTo: ${clientName}\nCSM: ${csmName}\n\n---\nSUBJECT: ${subject}\n\n${body}\n\n---\nGenerated by Flowbox CS Dashboard. Copy subject + body above and send from your HubSpot email compose.`

  try {
    // Use legacy engagements API — works without crm.objects.notes.write scope
    const associations: { associatedCompanyIds?: number[]; associatedDealIds?: number[] } = {}
    if (companyId) associations.associatedCompanyIds = [parseInt(companyId, 10)]
    if (dealId && dealId !== companyId) associations.associatedDealIds = [parseInt(dealId, 10)]

    const noteRes = await fetch(`${HS}/engagements/v1/engagements`, {
      method: 'POST',
      headers: auth(),
      cache: 'no-store',
      body: JSON.stringify({
        engagement: {
          active: true,
          type: 'NOTE',
          timestamp: Date.now(),
        },
        associations,
        metadata: {
          body: noteBody,
        },
      }),
    })

    if (!noteRes.ok) {
      const err = await noteRes.text()
      console.error('HubSpot engagement creation failed:', noteRes.status, err)
      return NextResponse.json({ error: `HubSpot ${noteRes.status}: ${err}` }, { status: 500 })
    }

    const note = await noteRes.json()
    const noteId = note.engagement?.id

    const portalId = process.env.HUBSPOT_PORTAL_ID ?? '8988558'
    // Open the deal page (shows note in activity feed) — fall back to company page
    const hubspotUrl = dealId && dealId !== companyId
      ? `https://app.hubspot.com/contacts/${portalId}/deal/${dealId}`
      : `https://app.hubspot.com/contacts/${portalId}/company/${companyId}`

    return NextResponse.json({ success: true, noteId, hubspotUrl })
  } catch (err) {
    console.error('Save to HubSpot error:', err)
    return NextResponse.json({ error: String(err) }, { status: 500 })
  }
}
