export const dynamic = 'force-dynamic'
export const runtime = 'nodejs'

import { NextRequest, NextResponse } from 'next/server'

// Map CSM first name → getflowbox.com email
// Adjust these to match your team's actual email addresses
const CSM_EMAILS: Record<string, string> = {
  claudia:  'claudia.nunez@getflowbox.com',
  cecile:   'cecile.gautier@getflowbox.com',
  sophia:   'sophia.jonsson@getflowbox.com',
  jerry:    'jerry.dewaart@getflowbox.com',
  chantal:  'chantal.vandenberg@getflowbox.com',
  frida:    'frida.lindqvist@getflowbox.com',
  oktawia:  'oktawia.gardecka@getflowbox.com',
  jana:     'jana.khoraizat@getflowbox.com',
  david:    'david.kupfer@getflowbox.com',
}

function getCsmEmail(csmName: string): string {
  const key = csmName.toLowerCase().trim().split(' ')[0]
  return CSM_EMAILS[key] ?? `${key}@getflowbox.com`
}

export async function POST(req: NextRequest) {
  if (!process.env.RESEND_API_KEY) {
    return NextResponse.json({ error: 'RESEND_API_KEY not configured' }, { status: 500 })
  }

  try {
    // Dynamic import so Resend isn't loaded at build time
    const { Resend } = await import('resend')
    const resend = new Resend(process.env.RESEND_API_KEY)

    const { subject, body, clientName, csmName } = await req.json()

    const csmEmail = getCsmEmail(csmName)

    const html = `
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8"/>
<style>
  body { font-family: Inter, Arial, sans-serif; background: #F5F5F7; margin: 0; padding: 24px; }
  .wrap { max-width: 600px; margin: 0 auto; }
  .banner { background: linear-gradient(135deg, #6A00FF, #AF79FE); border-radius: 12px 12px 0 0; padding: 20px 28px; }
  .banner-t { color: #fff; font-size: 13px; font-weight: 700; letter-spacing: .05em; text-transform: uppercase; opacity: .8; margin-bottom: 4px; }
  .banner-sub { color: rgba(255,255,255,.7); font-size: 12px; }
  .card { background: #fff; border: 1px solid #DFDFE5; border-top: none; border-radius: 0 0 12px 12px; padding: 28px; }
  .label { font-size: 10px; font-weight: 700; color: #A6A6B8; letter-spacing: .08em; text-transform: uppercase; margin-bottom: 6px; }
  .subj { font-size: 16px; font-weight: 700; color: #121217; margin-bottom: 24px; padding-bottom: 16px; border-bottom: 1px solid #ECECF0; }
  .body-text { font-size: 14px; color: #2D2D39; line-height: 1.75; white-space: pre-line; }
  .footer { margin-top: 28px; padding-top: 16px; border-top: 1px solid #ECECF0; font-size: 11px; color: #A6A6B8; }
  .note { margin-top: 20px; background: #F3EBFF; border: 1px solid #E4D1FF; border-radius: 8px; padding: 12px 16px; font-size: 12px; color: #5500CC; }
</style>
</head>
<body>
<div class="wrap">
  <div class="banner">
    <div class="banner-t">📋 AI-drafted retention email — for review</div>
    <div class="banner-sub">Client: ${clientName} · CSM: ${csmName}</div>
  </div>
  <div class="card">
    <div class="label">Subject</div>
    <div class="subj">${subject}</div>
    <div class="label">Body</div>
    <div class="body-text">${body}</div>
    <div class="note">
      ✦ This email was drafted by Claude and sent to your inbox for review.<br/>
      Copy the subject and body above, paste into your email client, and send directly to your client when ready.
    </div>
    <div class="footer">
      Generated by Flowbox Customer Health Dashboard · ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}
    </div>
  </div>
</div>
</body>
</html>`

    const { data, error } = await resend.emails.send({
      from: 'Flowbox CS Dashboard <noreply@getflowbox.com>',
      to: [csmEmail],
      subject: `[DRAFT for ${clientName}] ${subject}`,
      html,
    })

    if (error) {
      console.error('Resend error:', error)
      return NextResponse.json({ error: error.message }, { status: 500 })
    }

    return NextResponse.json({ success: true, sentTo: csmEmail, id: data?.id })
  } catch (err) {
    console.error('Send email error:', err)
    return NextResponse.json({ error: String(err) }, { status: 500 })
  }
}
