// TODO: replace with real API calls to HubSpot, Databricks (core.main.ugc_company_level_usage), and Chargebee (core.main.chargebee_subscriptions)

import { Client } from './types'

export const mockClients: Client[] = [
  // ── STABLE (score 75-95) ──────────────────────────────────────────────────
  {
    id: 'bestseller-001',
    name: 'Bestseller',
    arr: 280000,
    currency: 'DKK',
    csm: 'Adriana',
    healthState: 'stable',
    score: 91,
    confidence: 88,
    whyThisScore: 'Bestseller is a top performer. They published 142 posts last month with an 89% approval rate and distributed across 12 channels. Email cadence is strong with 8 exchanges in 30 days, and their last Fathom call confirmed ongoing expansion plans. Contract renewal is 9 months out.',
    recommendedAction: 'Schedule quarterly business review to discuss expanding to their new Vero Moda brand.',
    scoreDrivers: [
      { label: 'High post volume (142 posts/30d)', type: 'positive' },
      { label: 'Strong email engagement', type: 'positive' },
      { label: 'Positive expansion sentiment', type: 'positive' },
      { label: 'No open tickets', type: 'positive' },
    ],
    signals: {
      hubspot: { openTickets: 0, emails30d: 8, emails90d: 22, lastEmailIn: '2 days ago', lastEmailOut: '1 day ago' },
      usage: { posts30d: 142, approved30d: 126, distributed30d: 118, rightsRequests30d: 34, lastActiveDay: '2025-06-02' },
      chargebee: { status: 'active', contractEnd: '2026-03-01', cancelScheduled: false, dueInvoices: 0, totalDues: 0 },
      fathom: { sentiment: 'Very positive — discussed expanding to Vero Moda brand and adding 2 more markets.' },
    },
    contract: { start: '2024-03-01', renewal: '2026-03-01', ageMonths: 15 },
    renewalUrgent: false,
    lastContactDaysAgo: 1,
  },
  {
    id: 'vitakraft-002',
    name: 'Vitakraft',
    arr: 195000,
    currency: 'DKK',
    csm: 'Claudia',
    healthState: 'stable',
    score: 82,
    confidence: 85,
    whyThisScore: 'Vitakraft shows consistent usage with 98 posts and strong rights acquisition activity. Regular contact maintained with Claudia, and the recent call showed satisfaction with UGC performance for their pet food campaigns. Subscription is healthy with no payment issues.',
    recommendedAction: 'Share Q2 benchmark report and discuss seasonal campaign prep for autumn product launches.',
    scoreDrivers: [
      { label: 'Consistent monthly usage', type: 'positive' },
      { label: 'Active rights management', type: 'positive' },
      { label: 'Regular cadence maintained', type: 'positive' },
      { label: 'Renewal 11 months out', type: 'neutral' },
    ],
    signals: {
      hubspot: { openTickets: 0, emails30d: 5, emails90d: 16, lastEmailIn: '5 days ago', lastEmailOut: '3 days ago' },
      usage: { posts30d: 98, approved30d: 87, distributed30d: 79, rightsRequests30d: 56, lastActiveDay: '2025-06-01' },
      chargebee: { status: 'active', contractEnd: '2026-05-01', cancelScheduled: false, dueInvoices: 0, totalDues: 0 },
      fathom: { sentiment: 'Positive — happy with campaign results, interested in API integration.' },
    },
    contract: { start: '2024-05-01', renewal: '2026-05-01', ageMonths: 13 },
    renewalUrgent: false,
    lastContactDaysAgo: 3,
  },
  {
    id: 'bevivo-003',
    name: 'Bevivo',
    arr: 155000,
    currency: 'DKK',
    csm: 'Adriana',
    healthState: 'stable',
    score: 78,
    confidence: 82,
    whyThisScore: 'Bevivo is an established account with steady usage patterns and no churn signals. Post volume is moderate but consistent month-over-month. Last contact was 8 days ago which is slightly long but acceptable. Contract has 7 months remaining.',
    recommendedAction: 'Re-engage with best practice sharing session — usage could be increased with better workflow guidance.',
    scoreDrivers: [
      { label: 'Steady post volume', type: 'positive' },
      { label: 'No payment issues', type: 'positive' },
      { label: 'Contact gap 8 days', type: 'neutral' },
      { label: 'Below-avg distribution rate', type: 'neutral' },
    ],
    signals: {
      hubspot: { openTickets: 0, emails30d: 3, emails90d: 11, lastEmailIn: '8 days ago', lastEmailOut: '6 days ago' },
      usage: { posts30d: 67, approved30d: 58, distributed30d: 41, rightsRequests30d: 18, lastActiveDay: '2025-05-30' },
      chargebee: { status: 'active', contractEnd: '2026-01-01', cancelScheduled: false, dueInvoices: 0, totalDues: 0 },
      fathom: { sentiment: 'Neutral — satisfied but not actively expanding. Want to improve ROI visibility.' },
    },
    contract: { start: '2024-01-01', renewal: '2026-01-01', ageMonths: 17 },
    renewalUrgent: false,
    lastContactDaysAgo: 8,
  },

  // ── MODERATE (score 50-70) ────────────────────────────────────────────────
  {
    id: 'oenskeskyen-004',
    name: 'Ønskeskyen',
    arr: 120000,
    currency: 'DKK',
    csm: 'Adriana',
    healthState: 'moderate',
    score: 65,
    confidence: 78,
    whyThisScore: 'Ønskeskyen is 3 weeks into onboarding. Usage is growing but still below typical 30-day benchmarks. Team is engaged and completing training sessions. Early signals are positive but it is too early to fully assess health. All onboarding clients are classified as moderate minimum.',
    recommendedAction: 'Complete week 4 onboarding checklist. Schedule first content strategy session with their social team.',
    scoreDrivers: [
      { label: 'Early onboarding phase', type: 'neutral' },
      { label: 'Team engagement strong', type: 'positive' },
      { label: 'Usage below benchmark', type: 'negative' },
      { label: 'No churn signals', type: 'positive' },
    ],
    isOnboarding: true,
    signals: {
      hubspot: { openTickets: 1, emails30d: 12, emails90d: 12, lastEmailIn: '1 day ago', lastEmailOut: 'Today' },
      usage: { posts30d: 14, approved30d: 11, distributed30d: 6, rightsRequests30d: 2, lastActiveDay: '2025-06-03' },
      chargebee: { status: 'in_trial', contractEnd: '2026-06-01', cancelScheduled: false, dueInvoices: 0, totalDues: 0 },
      fathom: { sentiment: 'Positive onboarding energy — excited about campaign launch next month.' },
    },
    contract: { start: '2025-05-10', renewal: '2026-06-01', ageMonths: 1 },
    renewalUrgent: false,
    lastContactDaysAgo: 0,
  },
  {
    id: 'danish-design-005',
    name: 'Danish Design Store',
    arr: 175000,
    currency: 'DKK',
    csm: 'Claudia',
    healthState: 'moderate',
    score: 58,
    confidence: 72,
    whyThisScore: 'An open critical bug ticket is blocking their rights request workflow and has been unresolved for 9 days. This is dampening their ability to use key features. Usage has declined 28% in the last 14 days as a direct result. Email engagement remains good which suggests the relationship is intact.',
    recommendedAction: 'Escalate ticket #DDS-4421 to engineering today. Personally update Claudia with a resolution timeline.',
    scoreDrivers: [
      { label: 'Critical bug open 9 days', type: 'critical' },
      { label: 'Usage down 28% this week', type: 'negative' },
      { label: 'Email engagement intact', type: 'positive' },
      { label: 'Relationship healthy', type: 'neutral' },
    ],
    signals: {
      hubspot: { openTickets: 1, emails30d: 7, emails90d: 19, lastEmailIn: '2 days ago', lastEmailOut: '1 day ago' },
      usage: { posts30d: 43, approved30d: 31, distributed30d: 22, rightsRequests30d: 3, lastActiveDay: '2025-06-01' },
      chargebee: { status: 'active', contractEnd: '2025-12-01', cancelScheduled: false, dueInvoices: 0, totalDues: 0 },
      fathom: { sentiment: 'Concerned about the bug. They need the rights workflow fixed before their summer campaign.' },
    },
    contract: { start: '2024-12-01', renewal: '2025-12-01', ageMonths: 6 },
    renewalUrgent: false,
    lastContactDaysAgo: 1,
  },
  {
    id: 'nordisk-film-006',
    name: 'Nordisk Film',
    arr: 210000,
    currency: 'DKK',
    csm: 'Adriana',
    healthState: 'moderate',
    score: 52,
    confidence: 70,
    whyThisScore: 'Nordisk Film has shown a consistent decline in post volume over the past 60 days — down 41% from their Q1 peak. Email frequency has also dropped and the last Fathom call suggested internal restructuring may be affecting their social team capacity. No churn language but engagement is weakening.',
    recommendedAction: 'Request a discovery call to understand the restructuring impact. Propose a simplified workflow to reduce their operational overhead.',
    scoreDrivers: [
      { label: 'Post volume down 41% vs Q1', type: 'negative' },
      { label: 'Email frequency declining', type: 'negative' },
      { label: 'Internal restructuring signal', type: 'neutral' },
      { label: 'No payment issues', type: 'positive' },
    ],
    signals: {
      hubspot: { openTickets: 0, emails30d: 2, emails90d: 14, lastEmailIn: '12 days ago', lastEmailOut: '10 days ago' },
      usage: { posts30d: 31, approved30d: 24, distributed30d: 17, rightsRequests30d: 8, lastActiveDay: '2025-05-28' },
      chargebee: { status: 'active', contractEnd: '2026-02-01', cancelScheduled: false, dueInvoices: 0, totalDues: 0 },
      fathom: { sentiment: 'Neutral-negative — team has been reduced, harder to prioritize UGC right now.' },
    },
    contract: { start: '2024-02-01', renewal: '2026-02-01', ageMonths: 16 },
    renewalUrgent: false,
    lastContactDaysAgo: 10,
  },

  // ── ACTION REQUIRED (score 30-48) ─────────────────────────────────────────
  {
    id: 'elgiganten-007',
    name: 'Elgiganten',
    arr: 240000,
    currency: 'DKK',
    csm: 'Claudia',
    healthState: 'action_required',
    score: 42,
    confidence: 80,
    whyThisScore: 'Elgiganten has gone 34 days without meaningful contact despite multiple outreach attempts. Usage has dropped 52% compared to the same period last quarter. They have an overdue invoice of DKK 45,000. The combination of payment delay and disengagement is a serious risk signal.',
    recommendedAction: 'Escalate to Claudia\'s manager. Send a direct personal email today and flag the overdue invoice to finance.',
    scoreDrivers: [
      { label: 'No contact in 34 days', type: 'critical' },
      { label: 'Usage down 52% QoQ', type: 'critical' },
      { label: 'Overdue invoice DKK 45k', type: 'negative' },
      { label: 'No churn language yet', type: 'neutral' },
    ],
    signals: {
      hubspot: { openTickets: 0, emails30d: 0, emails90d: 7, lastEmailIn: '34 days ago', lastEmailOut: '28 days ago' },
      usage: { posts30d: 18, approved30d: 11, distributed30d: 7, rightsRequests30d: 1, lastActiveDay: '2025-05-10' },
      chargebee: { status: 'active', contractEnd: '2025-11-01', cancelScheduled: false, dueInvoices: 1, totalDues: 45000 },
      fathom: { sentiment: null },
    },
    contract: { start: '2024-11-01', renewal: '2025-11-01', ageMonths: 7 },
    renewalUrgent: true,
    lastContactDaysAgo: 34,
  },
  {
    id: 'illums-008',
    name: 'Illums Bolighus',
    arr: 155000,
    currency: 'DKK',
    csm: 'Adriana',
    healthState: 'action_required',
    score: 35,
    confidence: 75,
    whyThisScore: 'Illums Bolighus has been nearly inactive for 6 weeks with only 9 posts this month. Their social media manager left the company and the replacement has not yet been trained. Contact has been sporadic and there is no plan in place to restart campaigns. Their contract renews in 48 days.',
    recommendedAction: 'Offer a complimentary onboarding session for the new social media manager. Book within this week to prevent further attrition.',
    scoreDrivers: [
      { label: 'Near-zero usage 6 weeks', type: 'critical' },
      { label: 'Key contact left company', type: 'negative' },
      { label: 'Contract renews in 48 days', type: 'negative' },
      { label: 'Sporadic email contact', type: 'negative' },
    ],
    signals: {
      hubspot: { openTickets: 0, emails30d: 1, emails90d: 6, lastEmailIn: '18 days ago', lastEmailOut: '15 days ago' },
      usage: { posts30d: 9, approved30d: 6, distributed30d: 4, rightsRequests30d: 0, lastActiveDay: '2025-05-20' },
      chargebee: { status: 'active', contractEnd: '2025-07-21', cancelScheduled: false, dueInvoices: 0, totalDues: 0 },
      fathom: { sentiment: 'The contact who attended all calls is gone. New person has not been introduced yet.' },
    },
    contract: { start: '2024-07-21', renewal: '2025-07-21', ageMonths: 11 },
    renewalUrgent: true,
    lastContactDaysAgo: 15,
  },

  // ── CHURN RISK (score 10-28) ──────────────────────────────────────────────
  {
    id: 'tonsser-009',
    name: 'Tonsser',
    arr: 95000,
    currency: 'DKK',
    csm: 'Claudia',
    healthState: 'churn_risk',
    score: 14,
    confidence: 92,
    whyThisScore: 'Tonsser has scheduled cancellation active as of last week. Usage has been near-zero for 2 months with only 3 posts in the last 30 days. All emails go unanswered. The cancellation is triggered by budget reallocation according to their last communication before going dark.',
    recommendedAction: 'Initiate executive save play immediately. Have Adriana\'s VP reach out directly. Consider a discounted renewal offer with proof-of-ROI pack.',
    scoreDrivers: [
      { label: 'Cancellation scheduled', type: 'critical' },
      { label: 'Near-zero usage 60+ days', type: 'critical' },
      { label: 'Emails unanswered', type: 'critical' },
      { label: 'Budget reallocation flagged', type: 'negative' },
    ],
    signals: {
      hubspot: { openTickets: 0, emails30d: 0, emails90d: 3, lastEmailIn: '42 days ago', lastEmailOut: '35 days ago' },
      usage: { posts30d: 3, approved30d: 2, distributed30d: 1, rightsRequests30d: 0, lastActiveDay: '2025-05-05' },
      chargebee: { status: 'non_renewing', contractEnd: '2025-07-01', cancelScheduled: true, dueInvoices: 0, totalDues: 0 },
      fathom: { sentiment: 'Last call: budget being cut, evaluating all tools. Didn\'t see enough ROI from UGC.' },
    },
    contract: { start: '2024-07-01', renewal: '2025-07-01', ageMonths: 11 },
    renewalUrgent: true,
    lastContactDaysAgo: 35,
  },
  {
    id: 'dyrenes-010',
    name: 'Dyrenes Beskyttelse',
    arr: 70000,
    currency: 'DKK',
    csm: 'Adriana',
    healthState: 'churn_risk',
    score: 21,
    confidence: 87,
    whyThisScore: 'Dyrenes Beskyttelse has expressed explicit churn language in the last Fathom call transcript — they stated they are "evaluating alternatives" and "may not continue". Usage has dropped 67% over 3 months and the CSM has had only one successful touchpoint in the last 6 weeks. Their low ARR makes a steep discount a viable save option.',
    recommendedAction: 'Send a personalized save email today with an ROI impact summary and offer a 20% loyalty discount for a 12-month renewal.',
    scoreDrivers: [
      { label: 'Explicit churn language in call', type: 'critical' },
      { label: 'Usage down 67% in 3 months', type: 'critical' },
      { label: 'Very low engagement', type: 'negative' },
      { label: 'Low ARR — discount viable', type: 'neutral' },
    ],
    signals: {
      hubspot: { openTickets: 0, emails30d: 1, emails90d: 4, lastEmailIn: '21 days ago', lastEmailOut: '19 days ago' },
      usage: { posts30d: 8, approved30d: 5, distributed30d: 3, rightsRequests30d: 0, lastActiveDay: '2025-05-22' },
      chargebee: { status: 'active', contractEnd: '2025-09-01', cancelScheduled: false, dueInvoices: 0, totalDues: 0 },
      fathom: { sentiment: 'Evaluating alternatives — may not continue. Not seeing value for their nonprofit use case.' },
    },
    contract: { start: '2024-09-01', renewal: '2025-09-01', ageMonths: 9 },
    renewalUrgent: true,
    lastContactDaysAgo: 19,
  },
]
