// TODO: replace with real HubSpot Contracts Pipeline (874052773) data
import { Client } from './types'

export const mockClients: Client[] = [
  {
    id: 'deal-001', companyId: 'co-001',
    name: 'Bestseller', arr: 28000, currency: 'EUR', csm: 'Claudia', csmOwnerId: '64994666', brand: null,
    healthState: 'stable', score: 88, confidence: 85,
    whyThisScore: 'Strong usage health (Good), recent contact 5 days ago, Active Contract stage.',
    recommendedAction: 'Maintain current cadence. Consider proposing Q3 QBR.',
    scoreDrivers: [
      { label: 'Usage: Good', type: 'positive', direction: 'stable' },
      { label: 'Contact 5 days ago', type: 'positive', direction: 'stable' },
      { label: 'Auto renewal ON', type: 'positive', direction: 'stable' },
    ],
    triggeredRules: [],
    signals: {
      deal: { stage: '1309169013', stageLabel: 'Active Contract', autoRenewal: true, closeDate: '2026-09-01', churnDate: null, communicatedChurnDate: null, reasonForChurn: null, lastContactDaysAgo: 5 },
      company: { serviceLevel: 'High', usageHealth: 'Good', churnRisk: false, npsStatus: 'Veteran', totalActiveFlows: 8 },
      onboarding: { active: false, daysInOnboarding: 0, stage: null },
      openTasks: 0, fathom: { summaries: null, openActionItems: 0 },
    },
    contract: { start: '2024-09-01', renewal: '2026-09-01', ageMonths: 21, noticePeriodMonths: null },
    renewalUrgent: false, lastContactDaysAgo: 5,
    hubspotDealUrl: 'https://app.hubspot.com/contacts/deals/deal-001', flowboxPlatformId: null,
  },
  {
    id: 'deal-002', companyId: 'co-002',
    name: 'Vitakraft', arr: 19500, currency: 'EUR', csm: 'Claudia', csmOwnerId: '64994666', brand: null,
    healthState: 'stable', score: 80, confidence: 82,
    whyThisScore: 'Fair usage, no negative signals, last contact 11 days ago.',
    recommendedAction: 'Share Q2 benchmark report before month end.',
    scoreDrivers: [
      { label: 'Usage: Fair', type: 'neutral', direction: 'stable' },
      { label: 'Contact 11 days ago', type: 'positive', direction: 'stable' },
      { label: '6 active flows', type: 'positive', direction: 'stable' },
    ],
    triggeredRules: [],
    signals: {
      deal: { stage: '1309169013', stageLabel: 'Active Contract', autoRenewal: true, closeDate: '2026-11-01', churnDate: null, communicatedChurnDate: null, reasonForChurn: null, lastContactDaysAgo: 11 },
      company: { serviceLevel: 'Medium', usageHealth: 'Fair', churnRisk: false, npsStatus: 'Veteran', totalActiveFlows: 6 },
      onboarding: { active: false, daysInOnboarding: 0, stage: null },
      openTasks: 0, fathom: { summaries: null, openActionItems: 0 },
    },
    contract: { start: '2024-11-01', renewal: '2026-11-01', ageMonths: 19, noticePeriodMonths: null },
    renewalUrgent: false, lastContactDaysAgo: 11,
    hubspotDealUrl: 'https://app.hubspot.com/contacts/deals/deal-002', flowboxPlatformId: null,
  },
  {
    id: 'deal-003', companyId: 'co-003',
    name: 'Ønskeskyen', arr: 12000, currency: 'EUR', csm: 'Claudia', csmOwnerId: '64994666', brand: null,
    healthState: 'keep_an_eye', score: 62, confidence: 75,
    whyThisScore: 'Client is in active onboarding (Implementation stage, 24 days). Usage not yet established.',
    recommendedAction: 'Complete week 4 onboarding checklist. Schedule first content strategy session.',
    scoreDrivers: [
      { label: 'Active onboarding (24d)', type: 'neutral', direction: 'stable' },
      { label: 'Usage not yet measured', type: 'neutral', direction: 'stable' },
      { label: 'Contact 2 days ago', type: 'positive', direction: 'stable' },
    ],
    triggeredRules: ['onboarding_active'],
    signals: {
      deal: { stage: '1309169013', stageLabel: 'Active Contract', autoRenewal: false, closeDate: '2027-06-01', churnDate: null, communicatedChurnDate: null, reasonForChurn: null, lastContactDaysAgo: 2 },
      company: { serviceLevel: 'Medium', usageHealth: 'None', churnRisk: false, npsStatus: 'Onboarding', totalActiveFlows: 0 },
      onboarding: { active: true, daysInOnboarding: 24, stage: 'Implementation' },
      openTasks: 1, fathom: { summaries: null, openActionItems: 1 },
    },
    contract: { start: '2025-06-01', renewal: '2027-06-01', ageMonths: 1, noticePeriodMonths: null },
    renewalUrgent: false, lastContactDaysAgo: 2,
    hubspotDealUrl: 'https://app.hubspot.com/contacts/deals/deal-003', flowboxPlatformId: null,
  },
  {
    id: 'deal-004', companyId: 'co-004',
    name: 'Nordisk Film', arr: 21000, currency: 'EUR', csm: 'Claudia', csmOwnerId: '64994666', brand: null,
    healthState: 'keep_an_eye', score: 55, confidence: 70,
    whyThisScore: 'Renewal in Progress stage. ARR is significant — needs active monitoring.',
    recommendedAction: 'Push for signed renewal this week. Prepare ROI summary.',
    scoreDrivers: [
      { label: 'Stage: Renewal in Progress', type: 'negative', direction: 'declining' },
      { label: 'High ARR client', type: 'neutral', direction: 'stable' },
      { label: 'Contact 9 days ago', type: 'neutral', direction: 'stable' },
    ],
    triggeredRules: ['renewal_in_progress'],
    signals: {
      deal: { stage: '1309169015', stageLabel: 'Renewal in Progress', autoRenewal: false, closeDate: '2026-07-15', churnDate: null, communicatedChurnDate: null, reasonForChurn: null, lastContactDaysAgo: 9 },
      company: { serviceLevel: 'High', usageHealth: 'Fair', churnRisk: false, npsStatus: 'Longterm', totalActiveFlows: 3 },
      onboarding: { active: false, daysInOnboarding: 0, stage: null },
      openTasks: 0, fathom: { summaries: 'Discussed renewal terms. Client wants to review pricing before committing.', openActionItems: 1 },
    },
    contract: { start: '2024-07-15', renewal: '2026-07-15', ageMonths: 23, noticePeriodMonths: null },
    renewalUrgent: true, lastContactDaysAgo: 9,
    hubspotDealUrl: 'https://app.hubspot.com/contacts/deals/deal-004', flowboxPlatformId: null,
  },
  {
    id: 'deal-005', companyId: 'co-005',
    name: 'Elgiganten', arr: 24000, currency: 'EUR', csm: 'Claudia', csmOwnerId: '64994666', brand: null,
    healthState: 'action_required', score: 38, confidence: 82,
    whyThisScore: 'No contact in 36 days and deal stage is Up for Renewal. Auto renewal is OFF — risk of losing this contract.',
    recommendedAction: 'Contact Elgiganten today. Prepare renewal proposal with competitive pricing.',
    scoreDrivers: [
      { label: 'No contact 36 days (Up for Renewal)', type: 'critical', direction: 'declining' },
      { label: 'Auto renewal OFF', type: 'negative', direction: 'declining' },
      { label: 'Usage: Poor', type: 'negative', direction: 'declining' },
    ],
    triggeredRules: ['up_for_renewal_no_contact_30d', 'auto_renewal_false_close_100d'],
    signals: {
      deal: { stage: '1309169014', stageLabel: 'Up for Renewal', autoRenewal: false, closeDate: '2026-08-01', churnDate: null, communicatedChurnDate: null, reasonForChurn: null, lastContactDaysAgo: 36 },
      company: { serviceLevel: 'Medium', usageHealth: 'Poor', churnRisk: false, npsStatus: 'Veteran', totalActiveFlows: 1 },
      onboarding: { active: false, daysInOnboarding: 0, stage: null },
      openTasks: 0, fathom: { summaries: null, openActionItems: 0 },
    },
    contract: { start: '2024-08-01', renewal: '2026-08-01', ageMonths: 22, noticePeriodMonths: null },
    renewalUrgent: true, lastContactDaysAgo: 36,
    hubspotDealUrl: 'https://app.hubspot.com/contacts/deals/deal-005', flowboxPlatformId: null,
  },
  {
    id: 'deal-006', companyId: 'co-006',
    name: 'Tonsser', arr: 9500, currency: 'EUR', csm: 'Claudia', csmOwnerId: '64994666', brand: null,
    healthState: 'churn_risk', score: 14, confidence: 92,
    whyThisScore: 'Deal stage is Communicated Churn (in Winback). Client actively considering cancellation.',
    recommendedAction: 'Initiate save play immediately. Escalate to management for executive outreach.',
    scoreDrivers: [
      { label: 'Stage: Communicated Churn', type: 'critical', direction: 'declining' },
      { label: 'No contact 42 days', type: 'critical', direction: 'declining' },
      { label: 'Usage: None', type: 'critical', direction: 'declining' },
    ],
    triggeredRules: ['communicated_churn_stage'],
    signals: {
      deal: { stage: '1309169016', stageLabel: 'Communicated Churn (in Winback)', autoRenewal: false, closeDate: '2026-07-01', churnDate: '2026-07-01', communicatedChurnDate: '2026-05-15', reasonForChurn: 'Budget cuts; ROI not clear', lastContactDaysAgo: 42 },
      company: { serviceLevel: 'Low', usageHealth: 'None', churnRisk: true, npsStatus: 'Veteran', totalActiveFlows: 0 },
      onboarding: { active: false, daysInOnboarding: 0, stage: null },
      openTasks: 0, fathom: { summaries: 'Last call: budget being reallocated. Leadership not convinced of UGC ROI.', openActionItems: 0 },
    },
    contract: { start: '2024-07-01', renewal: '2026-07-01', ageMonths: 23, noticePeriodMonths: null },
    renewalUrgent: true, lastContactDaysAgo: 42,
    hubspotDealUrl: 'https://app.hubspot.com/contacts/deals/deal-006', flowboxPlatformId: null,
  },
]
